apiVersion: v1
kind: Pod
metadata:
  name: podaccess
  namespace: kube-system
spec: 
  serviceAccountName: s3-read-access
  containers:
    - name: aws-cli
      image: amazon/aws-cli:latest
      command:
        - sleep
        - "3600"