apiVersion: v1
kind: Pod
metadata:
  name: podnoaccess
spec: 
  containers:
    - name: aws-cli
      image: amazon/aws-cli:latest
      command:
        - sleep
        - "3600"
#This will assume nodeidentity role