apiVersion: v1
kind: Pod
metadata:
  name: python-exec
spec:
  containers:
  - name: python-container
    image: python:3.9
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: "50m"
        memory: "50Mi"
