apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-presistent-volume-claim
  namespace: application
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
