apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::637423386220:role/eks-node-group-Roles
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-06-03T04:30:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "699"
  uid: f57d4491-deb8-44fb-b37f-bc472f022971
