apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::637423386220:role/eksctl-eksdemo1-nodegroup-eksdemo1-NodeInstanceRole-17HEunBiakbt
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-04-21T05:28:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1338"
  uid: a1df4369-f602-4b44-b225-4a8a6b5ca7b5
